name: on-push-publish-to-npm

on:
  workflow_call:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
